# Clase 1: 06-04

## - Introducción a Python -

### Variables Simples

- `str`: string
- `bool`: booleano
- `float`: flotante
- `int`: entero

### Variables Compuestas

- `list`: listas - son mutables - se representan con `[ ]`
- `tuple`: tuplas - son inmutables - se representan con `( )`
- `set`: conjunto de valores únicos - se representa con `{ }`
- `dict`: diccionario - funciona con clave-valor - se representa con `{key : value}`

In [2]:
#### Listas ####

Lista = ["Izzi", "Webito", 22, True] # Crear lista
Lista.append("Rey") # Agregar un elemento
Lista.pop(3) # Eliminar elemento, en el paréntesis se pone la posición del elemento que se quiere borrar - Acá eliminamos la posición 3, o sea, True
Lista

['Izzi', 'Webito', 22, 'Rey']

### Listas por Compresión

Sirve para crear nuevas listas a partir de iterables existentes en una sola línea de código. Se construye a partir de la siguiente estructura:

`nueva_lista = [expresión for elemento in iterable if condición]`

El siguiente ejemplo muestra una lista que considera números del 0 a 9, donde se considerarán en la lista solo aquellos que sean pares:

In [3]:
ListaCompresion = [i for i in range(10) if i%2 == 0]
ListaCompresion

[0, 2, 4, 6, 8]

### Diccionarios
Son estructuras de datos que almacenan pares `clave:valor` encerrados entre llaves {}.

In [4]:
Diccionario = {"Mark": {"Edad":19, "Ciudad": "Detroit", "Super": "Invencible"}, "Eve": {"Edad":18, "Ciudad": "Chicago", "Super": "Atom Eve"}}

print(Diccionario["Mark"]["Super"])
print(Diccionario["Eve"]["Super"])

Invencible
Atom Eve


### Condicionales

In [18]:
for Clave, Valor in Diccionario.items():
    if Valor["Edad"] >= 18:
        print(f"{Valor['Super']} es mayor de edad.")
    elif Valor["Edad"] < 18:
        print(f"{Valor['Super']} no es mayor de edad.")

Invencible es mayor de edad.
Atom Eve es mayor de edad.


### Excepciones: Controlar muchas variables

El bloque `try` contiene el código que puede generar un error, mientras que `except` define las acciones a tomar si dicho error ocurre, evitando que el programa se detenga abruptamente.

In [ ]:
try:
    print(Diccionario["Mark"]["Altura"]) # Esto va a dar Error, porque no existe Altura en el Diccionario de Mark
except Exception as E: # Capturar el Error en "E"
    print("ERROR:", E) # Imprimir el Error

ERROR: 'Altura'


### Bucles

Existen dos tipos de bucles, preferiblemente utilizar `for`, aunque también existe `while`.

In [31]:
for a in Diccionario.keys(): # Iterar sobre las Claves del Diccionario
    print("El civil", a, "es el superhéroe", Diccionario[a]["Super"])

El civil Mark es el superhéroe Invencible
El civil Eve es el superhéroe Atom Eve


### Lista por Compresión de Diccionario

En este caso seguimos la misma estructura, pero para cambiar las condiciones, dejaremos que sea superior a 18 la edad, así, solamente `Mark` podría entrar a esta lista según la condición.

In [33]:
listCompresion = [i for i in Diccionario.keys()
                  if Diccionario[i]["Edad"] > 18]
listCompresion

['Mark']

## - Introducción a Numpy -

Manipulación de matrices y tensores (matriz `n` dimensional)

In [35]:
# Primero, se importa la librería

import numpy as np

In [ ]:
# Escalares
scalar = np.array([-1.5])
scalar

array([-1.5])

### Arrays:

Son arreglos inmutables, no se pueden modificar sus elementos. Esa sería la diferencia con las listas que sí lo son.

In [ ]:
arreglo = np.array([1,2,3.5,4,5])
arreglo.dtype # Tipo de dato en el arreglo
# Según lo que exista, se ve que predomina, en este caso hay un puro float pero igual predomina por el resto.

dtype('float64')

Para ciertas operaciones como concatenación de arreglos, se utiliza `concat`, uniendo dos arreglos.

<b>Nota:</b> Cabe aclarar que debe existir algún predominante en caso de que se junten typos de datos. Por ejemplo si se combinan enteros con strings, entonces los strings van a predominar.

In [ ]:
array = np.array([1,2,3,4,5])
array2 = np.array(["Grande", "Erivo", "Bailey", "Goldblum", "Slater"])

array_combinado = np.concat([array,array2])
array_combinado

array(['1', '2', '3', '4', '5', 'Grande', 'Erivo', 'Bailey', 'Goldblum',
       'Slater'], dtype='<U21')

### Números Aleatorios
- Utilizando la función `seed`, con el código o número que se le representa, es una semilla, o sea una estructura ya construida y guardada. Lo que en sí, garantiza la reproducibilidad de este arreglo.

- Utilizando la función `rand`, esta considera una estructura `(filas, columnas)`, por lo que en este caso este arreglo tiene <b>1 fila</b> y <b>10 columnas</b>. Se consideran números aleatorios entre 0 y 1.

In [50]:
np.random.seed(42)
random_array = np.random.rand(1,10)
random_array

array([[0.37454012, 0.95071431, 0.73199394, 0.59865848, 0.15601864,
        0.15599452, 0.05808361, 0.86617615, 0.60111501, 0.70807258]])

Existen funciones para la <b>redimensión de los arreglos</b>, esto se logra con `reshape` siguiendo la misma estructura de `(filas, columnas)`.

In [56]:
changed_array = random_array.reshape(2,5)
changed_array

array([[0.37454012, 0.95071431, 0.73199394, 0.59865848, 0.15601864],
       [0.15599452, 0.05808361, 0.86617615, 0.60111501, 0.70807258]])

In [57]:
# Traspuesta del Arreglo
changed_array.T

array([[0.37454012, 0.15599452],
       [0.95071431, 0.05808361],
       [0.73199394, 0.86617615],
       [0.59865848, 0.60111501],
       [0.15601864, 0.70807258]])

### Unos y Ceros

- La funcion `ones` sirve para realizar un arreglo de solamente unos, pero siguiendo una estructura `(filas, columnas)`.

- La funcion `zeros` sirve para realizar un arreglo de solamente ceros, pero siguiendo una estructura `(filas, columnas)`.

In [58]:
Unos = np.ones((2,5))
Unos

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [66]:
Ceros = np.zeros((2,5))
Ceros

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [64]:
# Operaciones o Ruido a los Arrays
print(Unos * 2 + changed_array)

[[2.37454012 2.95071431 2.73199394 2.59865848 2.15601864]
 [2.15599452 2.05808361 2.86617615 2.60111501 2.70807258]]


In [65]:
# Desviación Estándar
print(f"La desviación estándar es: {changed_array.std()}")

# Varianza
print(f"La varianza es: {changed_array.std() ** 2}")

La desviación estándar es: 0.2996564407009436
La varianza es: 0.08979398245355813


### Creacion de Espacios Lineales

Primero tenemos `linspace`, que sirve para generar un vector o tensor de números equiespaciados dentro de un intervalo específico. Sigue la estructura a continuación:

`np.linspace(inicio, fin, cantidad)`

In [67]:
np.linspace(0,10,5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

Otro es `arange`, el cual sirve para lo mismo, pero en vez de poner la cantidad se pone el valor del paso. Sigue la estructura a continuación:

`np.arange(inicio, fin, paso)`

In [68]:
np.arange(0,10,0.5)

array([0. , 0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5, 5. , 5.5, 6. ,
       6.5, 7. , 7.5, 8. , 8.5, 9. , 9.5])

### Problemas de Ecuaciones con Matrices

In [70]:
arregloA = np.random.rand(3,3)
arregloA

array([[0.29214465, 0.36636184, 0.45606998],
       [0.78517596, 0.19967378, 0.51423444],
       [0.59241457, 0.04645041, 0.60754485]])

In [71]:
arregloB = np.random.rand(3,1)
arregloB

array([[0.17052412],
       [0.06505159],
       [0.94888554]])

Ahora, la función `linalg.solve` sirve para resolver el sistema de ecuaciones `Ax=B`, donde `A` es la matriz de coeficientes, `B` es el vector de términos independientes y `x` es el vector de incógnitas.

In [72]:
np.linalg.solve(arregloA,arregloB)

array([[-1.33131691],
       [-2.2471031 ],
       [ 3.03180239]])